### ISSUE TITLE
bindgen_test_layout_max_align_t test fails on i686 on cryptoki-sys crate

### ISSUE THREAD

**Issue by nullr0ute** [parallaxsecond/rust-cryptoki#12]
When running the tests with bindgen for i686 the tests fail due the size of max_align_t

<pre>
test bindgen_test_layout_max_align_t ... FAILED
failures:
---- bindgen_test_layout_max_align_t stdout ----
thread 'bindgen_test_layout_max_align_t' panicked at 'assertion failed: `(left == right)`
  left: `16`,
 right: `24`: Size of: max_align_t', /builddir/build/BUILD/cryptoki-sys-0.1.0/target/release/build/cryptoki-sys-3b2c9ff8efdc70bf/out/pkcs11_bindings.rs:3:71904
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
failures:
    bindgen_test_layout_max_align_t
test result: FAILED. 22 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
</pre>

**Comment by hug-dev** [comment]
Hey! Thanks for reporting, looks very similar to the same one you reported on `psa-crypto` ([here](https://github.com/parallaxsecond/rust-psa-crypto/issues/41)). We can apply the same fix.

**Comment by nullr0ute** [comment]
I figured it was probably similar, I had forgotten about that report, there's also the same issue on the tss-esapi-sys. Seems like a theme ;-)

**Comment by hug-dev** [comment]
Alright created a PR on both repos:
- https://github.com/parallaxsecond/rust-cryptoki/pull/13
- https://github.com/parallaxsecond/rust-tss-esapi/pull/215

By the way, are you compiling those crate with the `generate-bindings` feature? If you wanted we could add the targets to the list of supported ones so you wouldn't need the `bindgen` dependency.

**Comment by nullr0ute** [comment]
> By the way, are you compiling those crate with the `generate-bindings` feature? If you wanted we could add the targets to the list of supported ones so you wouldn't need the `bindgen` dependency.

Yes, on this only arm/aarch64/x86_64 was created, on tss-esapi-sys only x86_64 was created. We build for armv7/aarch64/i686/x86_64/ppc64le/s390x so we needed to use bindgen to generate the pieces for all the arches.
