### ISSUE TITLE
`#[hsm_test]` attribute/macro

### ISSUE THREAD

**Issue by baloo** [parallaxsecond/rust-cryptoki#121]
Hi there!

I ended up creating an `#[hsm_test]` macro to be able to write:
```rust
#[cfg(test)]
mod tests {
    use cryptoki::{context::Pkcs11, slot::Slot};
    use softhsm_test::hsm_test;

    #[hsm_test]
    fn test_foo(pkcs11: Pkcs11, slot: Slot) {
        assert!(false, "oh no!");
    }
}
```

This will run the tests in a dedicated subprocess, set up a dedicated softhsm configuration in a test dir, update environment variables to then run the test.

Do you have any interest for such a contribution? (this will be at least one extra crate because one is a `proc-macro`)

**Comment by wiktor-k** [comment]
> Do you have any interest for such a contribution? 

Good question. By "contribution" do you mean rewriting tests to use your macro? (This would have an advantage that there wouldn't be a time-dependency between them) Or do you mean having that macro as part of the crate?

In first case we could make the extra dependency a dev-dependency. In the second case if could be hidden behind a feature... Just a couple of thoughts :)

**Comment by baloo** [comment]
> Good question. By "contribution" do you mean rewriting tests to use your macro? (This would have an advantage that there wouldn't be a time-dependency between them) Or do you mean having that macro as part of the crate?

I guess both :) The original question was about shifting ownership (and maintenance burden) here. But it would make sense to use it too.

We can definitely get everything behind a `test-harness` feature flags, although I'm not sure how to get CI run here if it's necessary to run our own tests.

**Comment by wiktor-k** [comment]
I would gate it with something like `cfg(any(test, feature = "macros"))`. This way it would be available for tests, and also exposed if someone wants that using `macros` feature.

This way both scenarios are implementable.

I'll bring @ionut-arm here for opinion :)

**Comment by baloo** [comment]
ha right!

**Comment by ionut-arm** [comment]
Sorry, just catching up now...

> I would gate it with something like `cfg(any(test, feature = "macros"))`. This way it would be available for tests, and also exposed if someone wants that using `macros` feature.

Yeah, as pointed out in the PR, the `test` predicate is not set during integration tests... :] What we did in the past was to create a new feature called something like `testing` which we only use/set for these integration tests..

Otherwise I like the idea and the approach - commenting here instead of the PR. Thanks for putting in the effort! 🙏🏻

**Comment by wiktor-k** [comment]
> Yeah, as pointed out in the PR, the test predicate is not set during integration tests... :] What we did in the past was to create a new feature called something like testing which we only use/set for these integration tests..

One minor thing is that this macro may be useful in other contexts than our internal testing. On the other hand if it's called `testing` it's doesn't mean it's for internal use only... :thinking:

**Comment by baloo** [comment]
Yeah, this is kind of the reason I'm inclined to create two new crates:
 - cryptoki-tests-derive
   carries the actual proc-macro
 - cryptoki-tests
   brings all runtime dependencies of tests


that way cryptoki can `dev-dependency` on `cryptoki-tests` and also re-export the `#[hsm_test]` from within the `testing` feature.
Best of both world, only downside being: I now need two new crates?

**Comment by baloo** [comment]
Pushed the new implem to #123

**Comment by baloo** [comment]
won't work for non-unix targets like current solution.
