### ISSUE TITLE
UserNotLoggedIn calling decrypt after login....

### ISSUE THREAD

**Issue by hcldan** [parallaxsecond/rust-cryptoki#157]
I'm not terribly familiar with this stuff, but this seems pretty straight-forward, lol.

I have an app successfully using this module on my machine (sigh...).
I can get session, inspect slots, find tokens, login, and perform crypto operations just fine.

On a another user's machine, I can do all of the above, but when I try to call decrypt using the private key it throws a `UserNotLoggedIn` even though I successfully logged in immediately BEFORE calling decrypt.
The login threw no error.   I saw their software come up and prompt for the pin, yet I still get this error...   

Has anyone ever seen this before?

**Comment by wiktor-k** [comment]
What module do they use? Is it the same as yours?

Maybe they have special login requirements: https://docs.rs/cryptoki/latest/cryptoki/session/struct.Session.html#method.login

> NOTE: By passing None into login, you must ensure that the [CKF_PROTECTED_AUTHENTICATION_PATH](https://docs.rs/cryptoki-sys/0.1.4/x86_64-unknown-linux-gnu/cryptoki_sys/constant.CKF_PROTECTED_AUTHENTICATION_PATH.html) flag is set in the TokenFlags.

**Comment by hcldan** [comment]
The really frustrating thing is when I go to search the card for Private(true) objects... I can't see them unless I login.
When I login (in both cases) I can see the private objects.

When I try to use one to decrypt it works on mine, but it throws `Pkcs11(UserNotLoggedIn)` on theirs.

**Comment by hcldan** [comment]
I have read online about interference with other pkcs11 applications interfacing with the card:
https://github.com/MicrochipTech/cryptoauthlib/issues/149

But I don't know enough about how any of this works... is this something that an application can control itself or does all access to the card need to be handled in order to not get corrupted sessions?

**Comment by hcldan** [comment]
I got a client log of the program they use that supplies the pkcs11 driver...    it's a lot, but it looks like it might be something in their driver.  Contacting support.   I'll close this.
