### ISSUE TITLE
Signing and Verifying

### ISSUE THREAD

**Issue by hcldan** [parallaxsecond/rust-cryptoki#159]
I'm kind of at a loss for this, but maybe I'm missing something silly...

I'm trying to sign and then verify the signature
```rust
	let sig = session.sign(&Mechanism::RsaPkcs, key_handle, &digest)?;
	eprintln!("verify: {:?}", session.verify(&Mechanism::RsaPkcs, cert_handle, &digest, &sig));
```

I keep getting `verify: Err(Pkcs11(KeyTypeInconsistent))`

The cert is queried looking for all x509 certs capable of signing.
I get the Id attribute of the cert and look for Attribute::Private(true) Attribute::Id(id) and find the key.

I've looked at pkcs11 examples in c and such and it looks like this should work? Is my card just messed up?

**Comment by hcldan** [comment]
Need to search for the public key (not certificate) when using verify

**Comment by wiktor-k** [comment]
Yeah... in my experience the certs are there only for convenience of other clients and the card treats them as opaque blobs unusable to anything on card.
