### ISSUE TITLE
Test fails on 32 bit platforms

### ISSUE THREAD

**Issue by nullr0ute** [parallaxsecond/rust-cryptoki#19]
The following test fails of 32 bit platforms like i686/armv7:

<pre>
     Running `/usr/bin/rustc --crate-name basic --edition=2018 tests/basic.rs --error-format=json --json=diagnostic-rendered-ansi --emit=dep-info,link -C opt-level=3 -C embed-bitcode=no --test --cfg 'feature="generate-bindings"' --cfg 'feature="psa-crypto"' --cfg 'feature="psa-crypto-conversions"' -C metadata=583ee0dc93216851 -C extra-filename=-583ee0dc93216851 --out-dir /builddir/build/BUILD/cryptoki-0.1.1/target/release/deps -L dependency=/builddir/build/BUILD/cryptoki-0.1.1/target/release/deps --extern cryptoki=/builddir/build/BUILD/cryptoki-0.1.1/target/release/deps/libcryptoki-6bad776c5f6e9b13.rlib --extern cryptoki_sys=/builddir/build/BUILD/cryptoki-0.1.1/target/release/deps/libcryptoki_sys-fe431e2ca4694bb5.rlib --extern derivative=/builddir/build/BUILD/cryptoki-0.1.1/target/release/deps/libderivative-f9299b8cc86001df.so --extern hex=/builddir/build/BUILD/cryptoki-0.1.1/target/release/deps/libhex-b0aa3e37c6be2f6a.rlib --extern libloading=/builddir/build/BUILD/cryptoki-0.1.1/target/release/deps/liblibloading-7e373c2941651059.rlib --extern log=/builddir/build/BUILD/cryptoki-0.1.1/target/release/deps/liblog-6938a0e0f6e5755d.rlib --extern num_traits=/builddir/build/BUILD/cryptoki-0.1.1/target/release/deps/libnum_traits-c7ca9deddf3a72ee.rlib --extern psa_crypto=/builddir/build/BUILD/cryptoki-0.1.1/target/release/deps/libpsa_crypto-71db317aab3c8e33.rlib --extern secrecy=/builddir/build/BUILD/cryptoki-0.1.1/target/release/deps/libsecrecy-c0451c9c4cd66ea8.rlib --extern serial_test=/builddir/build/BUILD/cryptoki-0.1.1/target/release/deps/libserial_test-dbc26b919cafbd54.rlib --extern serial_test_derive=/builddir/build/BUILD/cryptoki-0.1.1/target/release/deps/libserial_test_derive-0641132783ca7cb9.so -Copt-level=3 -Cdebuginfo=2 -Clink-arg=-Wl,-z,relro,-z,now -Ccodegen-units=1 --cap-lints=warn`
error[E0277]: the trait bound `Ulong: From<u64>` is not satisfied
  --> tests/basic.rs:40:32
   |
40 |         Attribute::ModulusBits(modulus_bits.into()),
   |                                ^^^^^^^^^^^^^^^^^^^ the trait `From<u64>` is not implemented for `Ulong`
   |
   = help: the following implementations were found:
             <Ulong as From<u32>>
   = note: required because of the requirements on the impl of `Into<Ulong>` for `u64`
error[E0277]: the trait bound `Ulong: From<u64>` is not satisfied
  --> tests/basic.rs:93:32
   |
93 |         Attribute::ModulusBits(modulus_bits.into()),
   |                                ^^^^^^^^^^^^^^^^^^^ the trait `From<u64>` is not implemented for `Ulong`
   |
   = help: the following implementations were found:
             <Ulong as From<u32>>
   = note: required because of the requirements on the impl of `Into<Ulong>` for `u64`
</pre>

**Comment by hug-dev** [comment]
Thanks for the report. Will fix it and try to see if we can just compile the tests on the CI.

**Comment by hug-dev** [comment]
Simple fix in the other PR. Adding test compilation on the CI will require a bit more work as then you need a `.cargo/config` file with the C toolchain of all the targets.
