### ISSUE TITLE
session.login fails on MacOS Sonoma

### ISSUE THREAD

**Issue by kristian1108** [parallaxsecond/rust-cryptoki#191]
I'm trying to figure out how to login to a PKCS11 session on my new operating system. This used to work. I've update to the latest version of this crate.

This is the line of code that's failing:

```rust
let result = session.login(UserType::User, Some(&secret_pin));
```

This is the error message that's printed:

```
Assertion failed: (ret == 0), function digest_final, file boringssl_crypto_digests.m, line 41.
```

```
	mov    x2, x8                   
	bl     0x104f28a88                ; symbol stub for: memcpy
	ldr    x0, [sp, #0x8]           
	ldr    x8, [sp, #0x58]          
	adrp   x1, 9843                 
	add    x1, x1, #0xf48             ; rustc_hex::CHARS + 15760
	bl     0x104559c54                ; <core::result::Result<T,F> as core::ops::try_trait::FromResidual<core::result::Result<core::convert::Infallible,E>>>::from_residual at result.rs:1960
	b      0x104560f50                ; <+536> at session_management.rs:61:6
	ldr    x8, [sp, #0x10]          
	ldr    x2, [sp, #0x28]          
	ldr    x1, [sp, #0x20]          
	ldr    x0, [sp, #0x18]          
	ldr    x9, [sp, #0x50]          
	ldr    x3, [x9, #0x8]           
	str    x3, [x9, #0x40]          
	blr    x8                       
	bl     0x1045557a0                ; <cryptoki::error::rv::Rv as core::convert::From<u64>>::from at rv.rs:19
	ldr    x8, [sp, #0x58]          
	bl     0x104556794                ; cryptoki::error::rv::Rv::into_result at rv.rs:131
	b      0x104560f50                ; <+536> at session_management.rs:61:6
	ldr    x8, [sp, #0x58]          
	adrp   x0, 9843                 
	add    x0, x0, #0xf30             ; rustc_hex::CHARS + 15736
	bl     0x104559f38                ; <core::result::Result<T,F> as core::ops::try_trait::FromResidual<core::result::Result<core::convert::Infallible,E>>>::from_residual at result.rs:1960
	b      0x104560f50                ; <+536> at session_management.rs:61:6
	ldp    x29, x30, [sp, #0x1b0]   
	ldp    x28, x27, [sp, #0x1a0]   
	add    sp, sp, #0x1c0           
```

Can add more detail as a find it, but if anyone has ideas that'd be super helpful. Thanks!

**Comment by ionut-arm** [comment]
Hi,

I've tried running your code for reproducing, and it didn't crash for me - though this was on an M1 MacBook Air with MacOs Ventura. Let me upgrade to Sonoma, try again, and I'll get back to you on that.

**Comment by jippeholwerda** [comment]
I seem to remember having the same issue. It occurred after upgrading my Homebrew openssl version to 3.2.0. Somehow, that doesn't seem to be working well with the Homebrew version of SoftHSM.

I solved it by installing SoftHSM via the nix package manager. A team member solved it by compiling SoftHSM from source, pointing to the Homebrew openssl version: `./configure --with-openssl=/opt/homebrew/Cellar/openssl@3/3.2.0`
Weirdly, that does work. No idea why.

Good luck!

**Comment by jippeholwerda** [comment]
@kristian1108 I didn't run into that problem, but if I run your boring-reproduce example I too get a segmentation.

**Comment by microshine** [comment]
Today, I also encountered an error in Go while using the `C_Login` method in SoftHSM. The issue appeared after upgrading macOS from version 14 to version 15.

```
Assertion failed: (ret == 0), function digest_final, file boringssl_crypto_digests.m, line 41.
SIGABRT: abort
PC=0x7ff813b0dc52 m=0 sigcode=0
signal arrived during cgo execution

goroutine 1 gp=0xc0000061c0 m=0 mp=0x10d349f80 [syscall]:
runtime.cgocall(0x10d08d6f0, 0xc0000786c0)
        /Users/microshine/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.3.darwin-amd64/src/runtime/cgocall.go:167 +0x4b fp=0xc000078698 sp=0xc000078660 pc=0x10cea81ab
github.com/miekg/pkcs11._Cfunc_Login(0x7fa27b904170, 0x1, 0x1, 0x7fa27ba12230, 0x5)
        _cgo_gotypes.go:1237 +0x4c fp=0xc0000786c0 sp=0xc000078698 pc=0x10cffc62c
github.com/miekg/pkcs11.(*Ctx).Login.func2(0x7ff7b30bf345?, 0x1, 0x1, 0x7fa27ba12230, {0x7ff7b30bf345?, 0x5})
        /Users/microshine/go/pkg/mod/github.com/miekg/pkcs11@v1.1.1/pkcs11.go:1022 +0x7c fp=0xc000078708 sp=0xc0000786c0 pc=0x10cfff49c
```

I followed the recommendations described in the mentioned issue, and it resolved the problem.

Here is the script for building and installing SoftHSMv2 on macOS. Hopefully, it will be helpful to someone:

```bash
git clone git@github.com:softhsm/SoftHSMv2.git
cd SoftHSMv2
brew install automake libtool pkg-config cppunit openssl
./autogen.sh
./configure --with-openssl=$(brew --prefix openssl)
make
sudo make install
softhsm2-util --init-token --so-pin "12345678" --pin "123456" --slot 0 --label "Slot 0"
```

**Comment by psavva** [comment]
Facing the same problem today

**Comment by hug-dev** [comment]
If this is a SoftHSMv2 issue on MacOS 15.5+ there is not much the maintainers of `cryptoki` can do sadly...

@Jakuje does `kryoptic` support MacOS? Maybe we should re-direct people there since SoftHSMv2 seems to slowly have gone unmaintained... And also think about making it the default for testing in `cryptoki`?

**Comment by aivarl** [comment]
Updating in case someone else has this problem. The solution by @microshine does actually work, but with a slight modification to the configure command to use OpenSSL backend (I think the default is Botan):

./configure \
  --with-crypto-backend=openssl \
  --with-openssl="$(brew --prefix openssl)"
