### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by jippeholwerda** [parallaxsecond/rust-cryptoki#194]
Hi!

Would it be possible to release a new version? Anything I can do to help with that?

Cheers!

**Comment by gowthamsk-arm** [comment]
Hello. Sorry for the delay. Sure we can release a new version. Is there a specific feature/commit missing in v0.6.1 that you need?

**Comment by jippeholwerda** [comment]
Yes, I really would like a release containing https://github.com/parallaxsecond/rust-cryptoki/pull/183.
Thx!

**Comment by gowthamsk-arm** [comment]
Will get a few open PRs merged before publishing a new crate.

**Comment by gowthamsk-arm** [comment]
@ionut-arm considering this https://github.com/parallaxsecond/rust-cryptoki/pull/147#issuecomment-1830488651, should we go for a `v0.7.0` release?

**Comment by tgonzalezorlandoarm** [comment]
> Will get a few open PRs merged before publishing a new crate.

One of the changes included may be: https://github.com/parallaxsecond/rust-cryptoki/issues/195 ?

**Comment by nullr0ute** [comment]
I would also like a fix for #198 please :)

**Comment by gowthamsk-arm** [comment]
New crate is now published: https://crates.io/crates/cryptoki/0.7.0
