### ISSUE TITLE
PkcsOaepParams

### ISSUE THREAD

**Issue by salih-okur** [parallaxsecond/rust-cryptoki#195]
I need to get PkcsOaepParams hash algorithm but it is not pub and it has not try_from CK_RSA_PKCS_OAEP_PARAMS. Is there any work you will do on this in the near future?

**Comment by tgonzalezorlandoarm** [comment]
Hello @salih-okur , I see that there is a [new function](https://github.com/parallaxsecond/rust-cryptoki/blob/main/cryptoki/src/mechanism/rsa.rs#L162) defined. Is this not suitable for your needs?

**Comment by salih-okur** [comment]
Hi @tgonzalezorlandoarm , 
Actually ı need to access the hash_alg parameter of PkcsOaepParams. I am using from trait for Mechanism and ı am getting Mechanism::RsaPkcsOaep(params). But I want to perform different operations according to hash_alg type of PkcsOaepParams.Because of that ı need to access hash_alg value directly or by functions of impl.

**Comment by tgonzalezorlandoarm** [comment]
Hi @salih-okur , is this what you were looking for? #207
