### ISSUE TITLE
Issue with code comment

### ISSUE THREAD

**Issue by wiktor-k** [parallaxsecond/rust-cryptoki#25]
The following comment seems to be wrong:

https://github.com/parallaxsecond/rust-cryptoki/blob/916f9bbb208ba8a671c593a36313f09c60cd0255/cryptoki/src/functions/slot_token_management.rs#L86-L87

32 is used not because it's a code for space but because [the spec](https://www.cryptsoft.com/pkcs11doc/v230/pkcs11__all_8h.html#aC_InitToken) requires 32 bytes. Also: the space is encoded as a first argument (`b' '`) as the it is required that the label is space-padded.

**Comment by hug-dev** [comment]
I digged hard to find the reason for this but found it [here](https://github.com/hug-dev/rust-pkcs11/pull/16#discussion_r540267767) 😆 
Forgot to remove the comment so now it's very confusing. You are right, should be removed!
