### ISSUE TITLE
Resizing/Truncating returned lists

### ISSUE THREAD

**Issue by daxpedda** [parallaxsecond/rust-cryptoki#34]
`Pkcs11::get_slots_with_token`, `Pkcs11::get_all_slots` and `Pkcs11::get_mechanism_list` currently truncate returned lists to account for changed sizes between querying the size and getting the list, a typical race condition.

There are two problems with this currently:
- `Vec::resize` is used instead of `Vec::truncate` for `Pkcs11::get_slots_with_token` and `Pkcs11::get_all_slots`
- Lists can also increase in size, which returns an error, it might be better to put it in a `loop` until the correct size is established

**Comment by ionut-arm** [comment]
Reopening this as the original PR was merged by mistake and then nuked from `main`.
