### ISSUE TITLE
Give Wiktor and Mike the `Write` role

### ISSUE THREAD

**Issue by hug-dev** [parallaxsecond/rust-cryptoki#45]
Hi @wiktor-k, @mjb3279,

You both helped us a lot with this crate over the past few weeks/days. You showed your interest in increasing the functionnality of the `cryptoki` crate and making overall better for all. Your PRs are always high-quality 💯.
As discussed on the [community channel](https://github.com/parallaxsecond/community/blob/main/minutes/2021-09-21.md), we would like to give you the `Write` role on this repository.

You can find a definition of the `Write` role [here](https://docs.github.com/en/github/setting-up-and-managing-organizations-and-teams/repository-permission-levels-for-an-organization#repository-access-for-each-permission-level) but basically that means that you will be able to approve/merge pull-requests and tinker with the CI.

Would you accept 😄?

**Comment by wiktor-k** [comment]
Looks good to me :+1: :rofl: 

Thanks for considering me @hug-dev! That's definitely an honor for me :)

**Comment by mjb3279** [comment]
Wow!  I'll echo @wiktor-k's comment and say that is definitely an honor.

I would like to accept, however I'm not that plugged into the rest of the development within the parallax project, for example, I know that my changes are on the `devel` branch due to one of my PRs updating the `bindgen` dependency version which makes it out-of-sync with the rest of the parallax project.

Maybe I missed it (I haven't really ventured outside of this repo) but is there like an overall project guide or something that I should review in order to ensure I'm in sync with the rest of the projects.

Again, thank you for the honor! :)

**Comment by hug-dev** [comment]
> I would like to accept, however I'm not that plugged into the rest of the development within the parallax project, for example, I know that my changes are on the devel branch due to one of my PRs updating the bindgen dependency version which makes it out-of-sync with the rest of the parallax project.
>
> Maybe I missed it (I haven't really ventured outside of this repo) but is there like an overall project guide or something that I should review in order to ensure I'm in sync with the rest of the projects.

I think generally we should try to keep the child crates (`cryptoki`, `tss-esapi`, etc) independant of the general Parsec project. You shouldn't need to know anything about Parsec to help us maintaining the crate.
I think if there are still links in between the projects that might be because our release processes are not mature or complete enough. For example, we did not have a `devel` or releases branch before which makes it hard to not do code freezes on child crates when we want to release the main Parsec project...

Generally our contributing/release process documentation is available [here](https://parallaxsecond.github.io/parsec-book/contributing/index.html). Some parts might be too Parsec specific for now and maybe we should update them.
Those things are not fixed and we are happy to improve them!

In the meantime, gave you both the `Write` role and thanks again!
