### ISSUE TITLE
Current `pkcs11.h` is not up-to-date

### ISSUE THREAD

**Issue by mike-boquard** [parallaxsecond/rust-cryptoki#65]
The `pkcs11.h` header file in `crypto-sys` is not in conformance with [PKCS#11 v2.40 + errata 01](http://docs.oasis-open.org/pkcs11/pkcs11-base/v2.40/os/pkcs11-base-v2.40-os.html).  This should be updated to match what the current spec is.  We have two options:

1. Go through the file and add in the missing fields
2. Download latest header files from [oasis](https://docs.oasis-open.org/pkcs11/pkcs11-base/v2.40/errata01/os/include/pkcs11-v2.40/)
2a. Will need to either modify `pkcs11.h` or add in our own header files for the different architectures (really the big one is Windows with its `pragma` directives).

**Comment by legounix** [comment]
What speaks against updating the pkcs11.h file to what opensc is using currently? Diffing the two files they look quite similiar, maybe that's easier then adopting the oasis files?

**Comment by hug-dev** [comment]
The latest set of headers were added in #228!
