### ISSUE TITLE
Force cache flush?

### ISSUE THREAD

**Issue by ximon18** [parallaxsecond/rust-cryptoki#75]
I recently created [a PR for the Krill project](https://github.com/NLnetLabs/krill/pull/754) to switch from the `pkcs11` crate to the `cryptoki` crate and in doing so I discovered one piece of "functionality" which I couldn't (easily) keep:

From: https://github.com/NLnetLabs/krill/pull/754/files#diff-753b1eac0564748e7eb4cbe23d53f883084d5e4b7140a81efed610ebc0d3af67R322
```
        fn force_cache_flush(context: ThreadSafePkcs11Context) {
            // Finalize the PKCS#11 library so that we re-initialize it on next use, otherwise it just caches (at
            // least with SoftHSMv2 and YubiHSM) the token info and doesn't ever report the presence of the token
            // even when it becomes available.
            let _ = context.write().unwrap().finalize();
        }
```

So I'm not sure if this is even legal per the PKCS#11 specification. What was happening was that Krill lazily connects to the "HSM" via the PKCS#11 library and if unable to connect then for some classes of error it will retry, for others it will declare the backend unusable. 

With SoftHSMv2 and the YubiHSM PKCS#11 libraries I saw that if the token or slot were not initialized/ready/reachable when Krill first attempted to use the "HSM" that I could resolve the underlying issue but Krill would still be unable to connect until restarted. This seems to be because of some sort of caching in the PKCS#11 library being used. I discovered that calling `C_Finalize()` and then `C_Initialize()` again would "flush" this cache and permit Krill to connect to the HSM without requiring a restart of Krill.

With the significantly different interface offered by the `cryptoki` crate (at the current tip of `main`) compared to the `pkcs11` crate I wasn't quickly easily able to keep this functionality, but doubted if I should even try.

What's your view on this?

**Comment by ionut-arm** [comment]
> I discovered that calling C_Finalize() and then C_Initialize() again would "flush" this cache and permit Krill to connect to the HSM without requiring a restart of Krill.

Hmmm, as far as I know, we call `finalize` on the open context [when it's dropped](https://github.com/parallaxsecond/rust-cryptoki/blob/main/cryptoki/src/context/mod.rs#L68), and so our "public" version of `finalize` just takes ownership of the context and drops it. Presumably what you'd need is a method that calls `finalize` while allowing the user to keep ownership of the context?

**Comment by ximon18** [comment]
Yes, previously I could call finalize and still have the context and call initialize on it again, now I cannot do that. I expect I can change my code to be able to create a whole new context instance but if it's a valid pattern to finalize and re-initialize and if it is valid per the PKCS#11 spec and it actually has real world value then an alternate model that permits ownership to be retained might be good to have.

Have you not run in to this same issue yourselves?

**Comment by ximon18** [comment]
Note: Please don't block an 0.3.0 release on this point.

**Comment by ximon18** [comment]
Minor update: I've modified our code to test if finalizing and re-initializing works with `cryptoki` with the same benefit that I saw with the `pkcs11` crate but I've run out of time for today and am not working tomorrow, so actual testing will have to wait until next week.

**Comment by ximon18** [comment]
@ionut-arm: I've tested my changes and it seems to work, thanks!
