### ISSUE TITLE
Add `is_initialized()` to `Pkcs11`

### ISSUE THREAD

**Issue by ximon18** [parallaxsecond/rust-cryptoki#77]
I recently created [a PR for the Krill project](https://github.com/NLnetLabs/krill/pull/754) to switch from the `pkcs11` crate to the `cryptoki` crate and in doing so I discovered a missing piece of functionality: the `cryptoki` crate has no equivalent of the `pkcs11` crate [`is_initialized()](https://docs.rs/pkcs11/latest/pkcs11/struct.Ctx.html#method.is_initialized) function.

Of course I can track whether or not I have called initialized myself but that's extra work. Or alternatively add an `fn initialize_if_needed()` or enable `fn initalize()` to tolerate being already initialized, which would prevent the caller from having to check and then call initialize to avoid getting an already initialized error.

**Comment by ionut-arm** [comment]
I think we should both add `is_initialized` and make `initialize` idempotent.
