### ISSUE TITLE
How to test for supported functions?

### ISSUE THREAD

**Issue by ximon18** [parallaxsecond/rust-cryptoki#78]
I recently created [a PR for the Krill project](https://github.com/NLnetLabs/krill/pull/754) to switch from the `pkcs11` crate to the `cryptoki` crate and in doing so I discovered a difference: the `pkcs11` crate requires lots of the pointers returned by `C_GetFunctionList()` to be non-null when the library is loaded, while `cryptoki` delays validation of function pointers until they are invoked.

If I want to verify as early as possible, and without actually invoking the functions, which functions a loaded library supports, how can I do that with `cryptoki`?

**Comment by ionut-arm** [comment]
Hey, apologies for the late reply!

Indeed, that's not available right now. I'm thinking that an option would be to have an enum with variants for all the PKCS11 functions and to use that in a call like `check_if_fn_null`, which returns an error if it is indeed null. Does that sound reasonable? Could start with a non-exhaustive list of methods in that enum.

**Comment by ionut-arm** [comment]
Sure, or maybe a `fn is_fn_null(...) -> bool`. Do you have any preferences?

**Comment by ximon18** [comment]
I have a slight preference for testing for support rather than lack of support, and for keeping the term "null" out of the Rust API, though I'm not sure I can put forward strong arguments for either.
