### ISSUE TITLE
EDDSA contrib

### ISSUE THREAD

**Issue by fmorency** [parallaxsecond/rust-cryptoki#87]
Hello Cryptoki team!
Thanks for working on a Rust abstraction for PKCS#11!

Would you be open to a PR integrating EDDSA support? A project of mine needs it and might attempt to add it to your library since it doesn't seem supported at the moment.

Thanks!

**Comment by hug-dev** [comment]
Guess what... I was also added!! In https://github.com/parallaxsecond/rust-cryptoki/pull/140 :nerd_face:
