### ISSUE TITLE
Digest

### ISSUE THREAD

**Issue by fmorency** [parallaxsecond/rust-cryptoki#88]
Hi cryptoki!
Is it possible to perform a digest operation (ex. SHA256) on an HSM using cryptoki? I see a `TODO` in the code.

Is anyone actively working to implement this?
Thanks!
-F

**Comment by ionut-arm** [comment]
Hi again!

No, I don't think anyone is working on anything like that right now. We try to keep all streams of work public, so if there isn't an issue, PR, or discussion open about it, it's very unlikely someone is working on it. Thank you for getting in touch to confirm, though!

I actually had a question for you, too: what platform/hardware module are you using this crate with? I'm aware that some PKCS11 implementations do things _a bit_ differently, treat the spec a bit more loosely, so if you discover anything like that please feed it back, so we can at least document it.

**Comment by fmorency** [comment]
Hello Ionuț,
Thanks for the information, this is very helpful.

I am developing against SoftHSMv2 at the moment, but I will test on a Yubikey 5 NFC. Folks on my team also have Nitrokey HSM 2. I will let you know if we discover anything.

Best,
-F

**Comment by hug-dev** [comment]
Digest is now available :) It was added here: https://github.com/parallaxsecond/rust-cryptoki/pull/132
