### ISSUE TITLE
Add support for SHA-based KDFs for ECDH

### ISSUE THREAD

**Issue by beamer159** [parallaxsecond/rust-cryptoki#92]
PKCS11 defines the following EC KDFs:

* CKD_NULL
* CKD_SHA1_KDF
* CKD_SHA224_KDF
* CKD_SHA256_KDF
* CKD_SHA384_KDF
* CKD_SHA512_KDF

It looks like the only currently supported KDF is CKD_NULL:

https://github.com/parallaxsecond/rust-cryptoki/blob/617efa846d67755d48708eb74e3d8149e184e83e/cryptoki/src/mechanism/elliptic_curve.rs#L46-L51

**Comment by ionut-arm** [comment]
Hey! Thanks for the request - any chance you'd be up to contribute those?

**Comment by hug-dev** [comment]
https://github.com/parallaxsecond/rust-cryptoki/pull/239 does it for SHA256. It's not all you posted first but I guess we can close it after that, and re-open if more are still needed :)
